apiVersion: apps/v1
kind: Deployment
metadata:
  name: phenome-ml
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phenome-ml
  template:
    metadata:
      labels:
        app: phenome-ml
    spec:
      containers:
        - name: ml
          image: phenome-ml:latest
          args: ["ml-service"]
          ports:
            - containerPort: 50052
