apiVersion: v1
kind: Service
metadata:
  name: phenome-analytics
spec:
  selector:
    app: phenome-analytics
  ports:
    - port: 50051
      targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
  name: phenome-ml
spec:
  selector:
    app: phenome-ml
  ports:
    - port: 50052
      targetPort: 50052
