[tasks.check-crate-ui-core]
workspace = false
command = "cargo"
args = ["check", "-p", "phenome-ui-core"]

[tasks.test-crate-ui-core]
workspace = false
command = "cargo"
args = ["test", "-p", "phenome-ui-core"]
