[tasks.check-crate-ui-terminal]
workspace = false
command = "cargo"
args = ["check", "-p", "phenome-ui-terminal"]

[tasks.test-crate-ui-terminal]
workspace = false
command = "cargo"
args = ["test", "-p", "phenome-ui-terminal"]

[tasks.check-crate-ui-terminal-primer]
workspace = false
command = "cargo"
args = ["check", "-p", "phenome-ui-terminal", "--features", "primer-cli"]
