[tasks.check-crate-core-application]
workspace = false
command = "cargo"
args = ["check", "-p", "phenome-application"]

[tasks.test-crate-core-application]
workspace = false
command = "cargo"
args = ["test", "-p", "phenome-application"]
