[package]
name = "rotappo-application"
version = "0.0.1"
edition = "2024"
publish = false

[dependencies]
anyhow = "1.0.100"
rotappo-domain = { path = "../rotappo-domain" }
rotappo-ports = { path = "../rotappo-ports" }
